---
title: "👨🏾‍💻 About Me"
subtitle: More Information About Abdulwasiu Bamidele Popoola | <br>Founder | EduTechTainMent Ltd &reg;.
citation: false
---

## Intro

Welcome to my Weblog. This weblog is created with 💝 by **© EduTechTainMent**.

## About Me

I am Abdulwasiu Bamidele Popoola, a health professional and an EdTech consultant with a passion for education and ICT. I am a self-taught web developer, and data professional. I have chosen to focus more on Artificial Intelligence and its varied applications in the healthcare industry. Given the current pervasive applications of AI, I hope to be able to contribute, in my own little way, to the AI landscape in my country and the globe at large. I am a passionate learner and show utmost dedication and grit when I put my mind to learning a skill. As a result I sought to become a self-taught data scientist by starting out as a data analyst. This will serve to equip me with the necessary analytical skills to succeed in data science. I believe learning is a step-wise but life-long process. Over the years I have worked to gather the requisite soft and technical skills to make me succeed in this endeavour. Given the importance of domain knowledge and expertise, I believe my wealth of experience in healthcare, better positions me to perform as an excellent health data analyst and ultimately a data scientist.

I love leveraging the use of technology in delivering educational content and also exploring applications of ICT in my medical workflow. This pushed me to acquire relevant skills to become an EdTech and HealthTech consultant. I therefore developed my personal Learning Management System (LMS) by using an open source tool - Moodle. I organize several trainings and workshops for academic staff members and health carwe workers to build capacity in EdTech/HealthTech and E-Learning content development.

A.B. Popoola is the immediate past Director of Health Services, University Health Services, Federal University Dutse (FUD). He is also an adjunct Lecturer, Dept. of Human Physiology, Faculty of Basic Medical Sciences, College of Medicine and Allied Medical Sciences, FUD. He is a Google Certified Data Analyst, took part in the Hamoye Data Science Fellowships ‘22 and '24, a DLYA certified in Data Science and Machine Learning, an ALX-T Udacity Certified Data Analyst, I4GxZuri Full Stack Software Developer, IBM Certified in Python for Data Science and AI, a McKinsey Forward Alumnus, INCO Certified in Green Digital Skills, DataCamp Certified in AI Fundamentals, DataCamp Certified in AI Literacy, Udacity Certified in AWS Machine Learning Foundations.

A. B. Popoola is a member of the Nigerian Medical Association (NMA), Member, Blacks in Technology, Nigeria and a Member, Data Science Network (DSN). I am also a DataCamp Classrooms Ambassador, Federal University Dutse and sole administrator of DataCamp Classrooms scholarships at FUD, mentoring, teaching and administering DataCamp scholarships to students of the university to help them gain globally relevant data skills. In addition, I am also a data mentor to many other students, and staff members, both within and outside the university.

I have a passion to teach, impart knowledge and network with like minds both in health sector and the IT domain. Thus I Founded EduTechTainMent Ltd (ETTM), an EdTech company that is involved in leveraging the use of technology in education and is the developer and administrator of [EduTechTainMent forum](https://edutechtainment.net), [EduTechTainMent Learning Management System](https://lms.edutechtainment.net) and [EduTechTainMent YouTube channel](https://www.youtube.com/@edutechtainmentguides).

I am also a member of the team that won a TETFund grant to develop an AI powered system to revolutionize medical education in Nigeria (powered by Anatomia Ltd.)

## Current Programs/Activities

1.  TechUp Africa Mentorship program with premium access to [DataQuest](https://dataquest.io). Now Completed ✅
2.  Arewa Data Science Program on DataCamp
3.  [Arewa Deep Learning Scholarship](https://arewadatascience.github.io/). Now Completed ✅
4.  [DataCamp Scholarship](https://datacamp.com) by TechUp Africa Now Completed ✅
5.  Lecturer for Postgraduate students of the Department of Economics and Development Studies for the professional postgraduate diploma in health economics, professional and academics Masters Program in Health Economics.
6.  Adj. Lecturer in the Department of Human Physiology, Faculty of Basic MedicalSciences, FUD taking undergraduate students of MBBS, Human Physiology, Human Anatomy, Public Health, Environment Health, and Nursing programs.
7.  Course Team Lead, and course facilitator for the Certificate in AI (for Teaching and Research), Applied Bioinformatics courses and other courses offered by the Centre for Biotechnology Research (CBR), Bayero University Kano.
8.  Organizing virtual weekly capacity building on the use of AI tools in teaching and research, and data analysis.

## Contributions and Public Events

We won a grant (in collaboration with colleagues from BUK) from The Physiological Society, UK, to organize the [Physiology Career Awareness and Training Initiative 2025 (PCATI-2025)](https://waga43.github.io/PCATI-2025). The PCATI-2025 workshop was an innovative idea aimed at creating awareness about the diverse applications and career options in medical physiology, improving research and training capacity for both students and faculty, across all medical schools in Nigerian universities.

In an effort to give back to the society, I am currently mentoring many students in FUD and other Nigerian universities, including university staff members in FUD and Nigeria at large. I hold regular training sessions to teach people various in-demand tech skills. Some of my mentees have made their marks in the data niche in Nigeria.

Furthermore, I am a [DataCamp for Classrooms](https://datacamp.com) ambassador for Federal University Dutse and the administrator of the DataCamp for Classrooms scholarship scheme for my students in FUD. This affords my students the opportunity to learn and acquire globally-relevant skills in tech and particularly data field.

In recognition of my skills, knowledge, contribution, and passion for the advancement of the use of data driven insights to drive medical education and innovation, I have delivered several public lectures and organised workshops teaching Edtech and HealthTech skills. I was invited as a panelist, guest speaker or workshop facilitator at several events some of which include:

1.  The Nigeria Medical Association (NMA) National Executive Council (NEC 2024) meeting in Kanem Borno during which I delivered a paper on **Artificial Intelligence (AI) and Health: Prospects and Challenges in Low- and Middle- Income Countries**.

2.  Bayero University Medical Students Association (BUMSA) **Artificial Intelligence (AI) Symposium** Lectures on:

    -   AI Fundamentals
    -   Responsible use of AI by medical students and Professionals
    -   How to be AI Professional in Medicine: Resources, Guides and Mentorship

3.  Aminu Kano Teaching Hospital College Foundation Day (CFD) 2024 Lecture on: **Ethical and Legal Implications of AI in Healthcare**

4.  The Nigerian Medical Association (NMA) Jigawa State chapter, Scientific Conference and Annual General Meeting (AGM) paper on: **The Emergence of Artificial Intelligence and How it can Help in Modern Medical Practice.**

5.  The Nigerian Medical Association (NMA) Kano State chapter Annual General Meeting (AGM) Lecture on **Application of Basic Artificial Intelligence (AI) in Medical Profession/Practice**

6.  Kano Medical Students Association (KAMSA) Journal paper titled: **The Rise of Telemedicine and Artificial Intelligence in Healthcare: A Boon or a Bane**.

7.  Guest speaker at the KAMSA Health Week 2025, with the theme: **The Emerging Landscape of Healthcare: Collaborative Intelligence.**

8.  Won a grant from the **Physiological Society, UK**, to organize the **Physiology Career Awareness and Training Initiative 2025 (PCATI-2025) workshop**. As a member of the team that won the grant, I was one of the Program Coordinators for The Physiological Society, UK-funded Physiology Career Awareness and Training Initiative 2025 (PCATI-2025). The PCATI-2025 workshop was an innovative idea aimed at creating awareness about the diverse applications and career options in medical physiology, improving research and training capacity for both students and faculty, across all medical schools in Nigerian universities.

9.  Workshop facilitator on the **Use of Learning Management System (LMS) for Innovative Teaching and Learning during the [PCATI-2025 program](https://waga43.github.io/pcati-2025/)**.

10. I was also invited by the Department of Human Physiology, BUK and the Center for Biotechnolgy Research (CBR), BUK, to organize/facilitate a workshop on Use of AI tools and Web Apps in **Designing Interactive E-Learning Courses & Use of Moodle LMS for Dynamic, and Immersive Teaching & Learning**.

11. One of the panelists/discussants in the Nigeria Medical Association, Jigawa - FutureMap Foundation, Kidney Health Week themed: **Advancing Kidney Health Through Digital Innovation**. During the event, an AI-driven Digital Kidney Wallet to screen for chronic kidney disease was launched.

12. Moderator of the panel discussion during the National Association of Jigawa Medical Students (NAJIMS) National Body Health Week themed: **Crossing Borders: The Japaa Dilemma Unveiled - A Clash of Convictions and Perspectives** on 11th May 2025.

13. Workshop facilitator and guest speaker at a 3-days workshop (17th to 20th December 2025) on **Artificial Intelligence (AI) Applications in Cancer Care in Nigeria** organised by the National Institute of Cancer Research and Treatment (NICRAT), Abuja, in collaboration with Aminu Kano Teaching Hospital (AKTH).

14. Guest speaker on: **Technology in Healthcare** at the World Family Doctor Day Celebration organised by the **Society of Family Physicians of Nigeria (SOFPON)**, Kano state chapter, Saturday 23rd May 2026.

A. B. Popoola is also actively involved in community development. Due to his passion to give back to the community, he got the management of FUD to approve the establishment of a Public Health Unit under the directorate of health services. He has been actively involved in many health initiatives and outreaches too many to mention, working in collaboration with Civil Society Organizations/Non-Governmental Organizations, student associations, and other partners in health.

------------------------------------------------------------------------

------------------------------------------------------------------------

```{=html}
<script async data-uid="40bd643e9c" src="https://edutechtainment.kit.com/40bd643e9c/index.js"></script>
```

------------------------------------------------------------------------

------------------------------------------------------------------------

::: callout-important
## Motto

> "Over Every Possessor of Knowledge, There is (Some) One (Else) More Knowledgeable"
:::